---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common','python-pip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=present
      
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Mysql Docker image
      docker_image:
        name: mysql
        source: pull

    - name: Create Mysql container
      docker_container:
        name: mysql_11
        image: mysql
        state: started
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: namptit 
          MYSQL_USER: nam
          MYSQL_PASSWORD: namptit
          MYSQL_DATABASE: wordpress
        restart: true

